### ISSUE TITLE
files in /terraform folder are different 

### ISSUE THREAD

**Issue by Edwintenhaaf** [ksatirli/enhancing-infrastructure-lifecycles#3]
Hi Kerim.

Thanks for the informative workshop yesterday at converge!
I managed to follow the first part but got behind the second half.
This morning i'm trying to catchup using the recording and the filled in terraform files in the  /terraform folder as you mentioned during the workshop.
The files differ and the recording is low quality so I can't see the code you're typing.
![image](https://user-images.githubusercontent.com/51457250/138833509-51297a95-7030-4901-bd27-8f7258276c8c.png)

Can you help me -and others- out on this ?

Thanks in advance,

Edwin

**Comment by ksatirli** [comment]
Hey @Edwintenhaaf,

Thanks for reaching out and joining the workshop yesterday.

The files in `./terraform` are indeed a bit different when compared to `./workshop`.

`./workshop` was derived from `./terraform` but had the actual Terraform code removed in favor of comments to trigger you to find the right solution.

Are you looking for the complete solution to the workshop or just a single step?

**Comment by Edwintenhaaf** [comment]
Hi Kerim,

I already figured out the settings needed.
As if it was difficult to read this was a challenge but I succeeded.
I tried running the 'terraform apply' from the /terraform folder but it
failed because of ssh keys that were missing.
So no help needed anymore, looking forward to your packer session later this
week at converge.

Kind regards,

Edwin

**Comment by ksatirli** [comment]
Great news!
